### ISSUE TITLE
Overide visit creating error. 

### ISSUE THREAD

**Issue by Beckdotan** [ncalc/ncalc#177]
Hi, so as part of the transition, not I tried the V4.1.0 and I got to the problem when trying to declare my own visit function: 
`		public override void Visit(BinaryExpression expression)
`

and got the error:
` 'Program.MyVisitor.Visit(NCalc.Domain.BinaryExpression)': cannot override inherited member 'NCalc.Visitors.EvaluationVisitor.Visit(NCalc.Domain.BinaryExpression)' because it is not marked virtual, abstract, or override
` 
 here is the full code for reference: 
 https://dotnetfiddle.net/yuaMSK
 
 Thanks for the quick help!

**Comment by gumbarros** [comment]
Hello @Beckdotan 

You have two options

Change the override to new

Or

Change EvaluationVisitor to IEvaluationVisitor

**Comment by Beckdotan** [comment]
@gumbarros Thanks. changed the override to new (the other changed caused some more errors), but now when trying to run I get this error:
Run-time exception (line 68): Operation could destabilize the runtime.

Stack Trace:

[System.Security.VerificationException: Operation could destabilize the runtime.]
   at NCalc.Expression.set_LogicalExpressionCache(ILogicalExpressionCache value)
   at NCalc.Expression..ctor()
   at NCalc.Expression..ctor(String expression, ExpressionContext context)
   at NCalc.Expression..ctor(String expression, ExpressionOptions options, CultureInfo cultureInfo)
   at Program.EvaluateArray(String expression, Dictionary`2 parameters) :line 68
   at Program.Main() :line 26


line 68 is :
		`var exprForParameters = new Expression (expression,  ExpressionOptions.CaseInsensitiveComparer); // Added for v4 to check the unique parameters in the expression. `

**Comment by gumbarros** [comment]
I think `new` causes this exception for security reasons. I think you need to implement `IEvaluationVisitor` and copy from `EvaluationVisitor` source code what you need.
