### ISSUE TITLE
occur exception when using chinese characters in parameters

### ISSUE THREAD

**Issue by wapco** [ncalc/ncalc#348]
Hi, i get this exception when using chinese characters in parameters:

        string exp = "2 * 参数1";
        Expression e = new Expression(exp);
        e.Parameters["参数1"] = 5;
        var v = e.Evaluate();

exception:
NCalc.Exceptions.NCalcParserException: Error parsing the expression.
       ---> NCalc.Exceptions.NCalcParserException: Invalid token in expression at position (1:2)
         at NCalc.Parser.LogicalExpressionParser.Parse(LogicalExpressionParserContext context)
         at NCalc.Factories.LogicalExpressionFactory.Create(String expression, ExpressionOptions options)
         at NCalc.Factories.LogicalExpressionFactory.NCalc.Factories.ILogicalExpressionFactory.Create(String expression, ExpressionOptions options)
         --- End of inner exception stack trace ---

**Comment by Bykiev** [comment]
Hi, you should use a square brackets in expression:
`string exp = "2 * [参数1]";`

**Comment by wapco** [comment]
It works normally. Thank u!
